//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int ID { get; set; }
        public int Growth { get; set; }
        public int Weight { get; set; }
        public int Age { get; set; }
        public bool Gender { get; set; }
        public Nullable<double> HowMuchKkal { get; set; }
        public Nullable<double> HowMuchKkalToday { get; set; }
        public Nullable<int> HowMuchMinuteNow { get; set; }
    }
}
